### ISSUE TITLE
Support for TypeScript template and eject command 

### ISSUE THREAD

**Issue by fox1t** [fastify/fastify-cli#131]
Hi, guys. It will be nice to include in fastify-cli support for TypeScript projects. 
In order to generate a TS  project we need to change some of the current fastify-cli's commands and to add one new:
 * `start`       start a server -> here we can add support for .ts files  (auto-discover file extension), add default tsconfig.json file with default compilation rules and use ts-node with inline sourcemap generation to run the code. Notes: Running .ts is not intended for production environment, .ts files will be inside `/src` folder, as this is a TS standard defacto.
  * `generate`   generate a new project -> we need to add new arg `--typescript` (`-ts`) to generate TypeScript project with all dependencies and to add to `package.json` typings and typescript compiler. In addition we need (just one?) new npm-script to build .ts code.
  * `eject`   ejects the app (__new command__) ->  creates server.ts file and compiles all TypeScript code from src to `build` (or `dist`) folder and modifies scripts to use newly generated paths. Note: this command could be used also by JS projects.

In addition to that, what do you think to add one more new npm-script for running debugger `in package.json`? It would be nice to have it ready inside package.json.

I am looking forward for ideas and I am ready to implement this feature,

**Comment by delvedor** [comment]
> generate generate a new project -> we need to add new arg --typescript (-ts) to generate TypeScript project with all dependencies and to add to package.json typings and typescript compiler. In addition we need (just one?) new npm-script to build .ts code.

I'm not sure you can do `-ts`, as it should be read as `-t -s` by the parser.

> eject ejects the app (new command) -> creates server.ts file and compiles all TypeScript code from src to build (or dist) folder and modifies scripts to use newly generated paths. Note: this command could be used also by JS projects.

This means that you should "eject" the app everytime you need to deploy to production? If so I don't like it too much, it feels more complex than it should be.

`fastify-cli` is intended to work both on prod and development, and it should continue to do so in my opinion.

> In addition to that, what do you think to add one more new npm-script for running debugger in package.json? It would be nice to have it ready inside package.json.

Can you post an example?

**Comment by cemremengu** [comment]
Sounds very nice actually! Currently we do eject manually (see README) so that would be a nice feature to have as well.

I would be happy to review a PR as long as it doesnt break current functionality for javascript.

**Comment by mcollina** [comment]
I'm +1 on adding support for ts.

**Comment by cemremengu** [comment]
My comment is gone I think I deleted it mistakenly on the phone but I am +1 as well.

**Comment by delvedor** [comment]
> Ok we can use just --typescript (and maybe --ts?) then.

I'll go with `--typescript` :)

> If we want to support fastify start with .ts in production, we need to run always .js fils. This implies that we can't use ts-node to compile on the fly TS code and we have to rely on build folder with .js files. This is not a big problem, but usually in TS projects you really build to js files only on linting/testing/before pushing fase and inside CI env, before Docker image build, for example. Eject is just helper to do automatically what you say here https://github.com/fox1t/fastify-cli#migrating-out-of-fastify-cli-start so we can implement it also without ts-node and TS specific stuff.

Maybe `npm run dev` could use `ts-node`, while `npm start` is prod only.
I'm not entirely sure that we would need eject to run the project even with typescript.

Regarding the `debug` script we remove the default linter (the old `npm run lint` command) because it was too opinionated, I fear this script could fall in the same category.

I didn't say this in my first comment, I'm definitely 👍 on typescript support :)

**Comment by fox1t** [comment]
Which nodejs versions are we targeting here? I need to know to set a correct default build target for TS.

**Comment by delvedor** [comment]
Node 6+

**Comment by fox1t** [comment]
The default will be "es2016". I'll update docs to mention that if node version is 8+ it is safe to put TS target to "es2017" and if it is 10+ "es2018" can be used.

**Comment by rkorrelboom** [comment]
Hi @fox1t,

Is there any news regarding this feature? I'm also exploring the options regarding this feature but if I could expand on any previous work it would make my life a lot easier :-)

So far I've managed to add a `--typescript` argument to the generate command and I'm able to run a generated typescript project with `ts-node`. I'm currently running into some issues with `fastify-autoload` and `ts-node` where `fastify-autoload` isn't picking up `.ts` files:
- We could add an extension option to `fastify-autoload` which would make it work with `ts-node`. But since the start command is also required to work in production (which requires a transpiled build), this would only work with some fancy build time replacements or runtime environment checking.
- Another option would be not to use `fastify-autoload` for the typescript templates, which would be much cleaner and easier in my opinion.

Any thoughts on this?

**Comment by fox1t** [comment]
Hi @rkorrelboom, unfortunatly i never found the time/excuse to work on this. :(
However it is great that you are implementing such a nice feature! I think that it is better to not use fastify-autoload. Supporting both, dev and prod, was also one of the major point of pain that I found, working on this.

**Comment by mcollina** [comment]
I think we should find a good typescript story for autoload, and then tackle this one. I don’t see much benefit of this structure without autoload.

**Comment by mcollina** [comment]
fastify-autoload now supports typescript, so we can add a typescript template here if we want to. Would you like to send a PR?

**Comment by wolfejw86** [comment]
One thing I noticed when manually refactoring a generated fastify-cli app to typescript is that if certain tsconfig.json properties are present, the `app.js` file gets compiled like so:
![image](https://user-images.githubusercontent.com/22133869/74308548-826d5f00-4d36-11ea-9054-5eeae6a70bec.png)
which causes it to break on line 120 of `fastify-cli/start.js` due to needing to call `file.default` instead of just `file`.  Has anyone worked around this?

**Comment by alemagio** [comment]
Hi, i wanted to use the cli for my own project and found out there is no TS support.
If no one else is working on this I would like to open a PR.

**Comment by JoHuang** [comment]
Hi, I tried the typescript generator but run into some issues.
Since this issue is not closed yet, so I add comment here.

------
I tried to install fastify-cli by `npm i -g git+https://git@github.com/fastify/fastify-cli.git` to get master branch.
And generated a typescript project by `fastify generate --lang=ts [project name]`.
Here are 2 issues I encountered:
1. 
https://github.com/fastify/fastify-cli/blob/555e7acc7d6c9f579bd73623f41d017a1a8049ea/generate.js#L48-L49
`build` should be `build:ts`


2. 
When I run `npm start`, I got error
```
/Users/apple/GitProject/myProject/node_modules/avvio/boot.js:194
    throw new Error('plugin must be a function or a promise')
    ^

Error: plugin must be a function or a promise
    at assertPlugin (/Users/apple/GitProject/myProject/node_modules/avvio/boot.js:194:11)
    at Boot._addPlugin (/Users/apple/GitProject/myProject/node_modules/avvio/boot.js:226:3)
    at Boot.use (/Users/apple/GitProject/myProject/node_modules/avvio/boot.js:202:25)
    at Object.server.<computed> [as register] (/Users/apple/GitProject/myProject/node_modules/avvio/boot.js:32:14)
    at runFastify (/Users/apple/GitProject/myProject/node_modules/fastify-cli/start.js:119:11)
    at start (/Users/apple/GitProject/myProject/node_modules/fastify-cli/start.js:50:10)
    at Command.cli [as func] (/Users/apple/GitProject/myProject/node_modules/fastify-cli/start.js:139:3)
    at Command.call (/Users/apple/GitProject/myProject/node_modules/commist/index.js:105:8)
    at Object.parse (/Users/apple/GitProject/myProject/node_modules/commist/index.js:54:19)
    at Object.<anonymous> (/Users/apple/GitProject/myProject/node_modules/fastify-cli/cli.js:25:21)
```
but if I only run `fastify start -l info dist/app.js`
It works without error.

Any idea would be helpful.
thanks

**Comment by alemagio** [comment]
Hi
I'm not a maintainer of the project but I made the PR to integrate TS.

I think that you pointed out the fix for this error, the `start` script should be `npm run build:ts ...`.

If you want to fix it I suggest you to go [here](https://github.com/fastify/fastify-cli/blob/f5e4da5f3b19744bf7a212854faaa359b3a55f1e/generate.js#L48) and simply edit that line and the relative test.

I'll cc @Ethan-Arrowood and @mcollina so if I said anything wrong they can punch me in the face :joy:

**Comment by JoHuang** [comment]
@alemagio
I forgot to clarify that the `'plugin must be a function or a promise'` error happened after I edited the line.
So it should be 2 separated issues.

**Comment by alemagio** [comment]
> @alemagio
> I forgot to clarify that the `'plugin must be a function or a promise'` error happened after I edited the line.
> So it should be 2 separated issues.

Probably

**Comment by JoHuang** [comment]
> Does the dev script work?

No, it's the same. Only `fastify start -l info dist/app.js` works.

**Comment by alemagio** [comment]
Ok, after some debugging I think I got the problem.
I think there is some issue in the `fastify-cli` installed in the generated project because, even if it says the version is `1.5.0` it misses some code (like all the typescript parts).
As a temporary fix (and also validate my hipotesis) please remove the `fastify-cli` package from your `node_modules` and run the start script again.
This way it should use your globally installed `fastify-cli` which is correct.

Please let me know.

**Comment by JoHuang** [comment]
After `npm uninstall fastify-cli`, which means using global one (from GitHub master branch)
`npm start` works
`npm run dev` got a new error.
```
/usr/local/lib/node_modules/fastify-cli/node_modules/pump/index.js:26
  stream.on('close', function () {
         ^

TypeError: stream.on is not a function
    at destroyer (/usr/local/lib/node_modules/fastify-cli/node_modules/pump/index.js:26:10)
    at /usr/local/lib/node_modules/fastify-cli/node_modules/pump/index.js:70:12
    at Array.map (<anonymous>)
    at pump (/usr/local/lib/node_modules/fastify-cli/node_modules/pump/index.js:67:26)
    at runFastify (/usr/local/lib/node_modules/fastify-cli/start.js:101:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/fastify-cli/lib/watch/fork.js:12:17)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
```
BTW I'm using Mac OS X.

**Comment by alemagio** [comment]
This looks related to the `pretty-logs` option.
I solved by removing the `-P` option from the `dev` script.
It is not a fix off course but at least you can keep working.

**Comment by JoHuang** [comment]
It works by removing `-P`.

BTW, I recommend add `dist/` to `.gitignore`.

**Comment by alemagio** [comment]
Thanks for all the advices and glad to be helpful.
:smiley:

**Comment by alemagio** [comment]
There was already an issue about this. 
[Here](https://github.com/fastify/fastify-cli/issues/235)
