### ISSUE TITLE
`--cluster` flag

### ISSUE THREAD

**Issue by piranna** [fastify/fastify-cli#198]
## 🚀 Feature Proposal

Add support for a `--cluster` flag that allow to launch `fastify` using Node.js `cluster` module.

## Motivation

Node.js `cluster` module allow to exec several copies of a script in different processes sharing the same port, so with web servers you can make use of all cores.

## Example

At https://github.com/piranna/clusterify I have some generic code that exec any Node.js script wrapped with `cluster` module, but would be nice if `fastify` CLI would have native support.

**Comment by piranna** [comment]
Also, at https://gist.github.com/thearegee/3eea038b9f0c5e94de73f3c3482fa732 there's an example about how to use it natively.

**Comment by piranna** [comment]
Regarding `clusterify`, I'm able to use it to launch `fastify` CLI with

```sh
clusterify node_modules/.bin/fastify start index.js
```

**Comment by Eomm** [comment]
I think that this feature is not in scope for this module because it is in charge to any process manager, usually, with the cluster mode, it is needed also restart of child and logging management plus many other features (scaling, health check)

I used it a lot [pm2](http://pm2.keymetrics.io/) for this kind of needs and have a bunch list of utilities around it. The effort is to write a json file.

**Comment by piranna** [comment]
Ok, maybe make sense. I was a bit surprised being a launcher of `fastify` servers not having any reference to it, that maybe `fastify` itself didn't support `cluster` at all. At least the command using `clusterify` is doing me the job :-)
