### ISSUE TITLE
Add minimal eslint and Prettier configurations

### ISSUE THREAD

**Issue by veritem** [fastify/fastify-cli#363]
It would be great if for the generated code you added minimal eslint and prettier configurations as optional for people that need them in their work flow

**Comment by mcollina** [comment]
We did not do this on purpose as we could not really agree on these topics between ourselves.

What are the other folks in @fastify/fastify think? I'm happy to go with the majority.

(As an example, I dislike any use of prettier).

**Comment by zekth** [comment]
I think that have to be an option in the creation of a project like `Would you want to have code style configurations?`.
EG: in most of my projects i use eslint + editorconfig + prettier because of dayjob habits; but having those forced in a cli like in `vue-cli` or any other is a bit too intrusive to me. I personnaly don't mind of the code style as the scripts in `package.json` are implemented like `lint` and `lint:fix`

**Comment by Eomm** [comment]
I agree with the optional flag to turn on this feature

Someone else who prefer another setup (es: `standardjs`) shall submit a PR 👍🏽

**Comment by meehawk** [comment]
@mcollina I would love to work on this if it is still open. Trying to get more contributions to fastify in 😁

**Comment by UltiRequiem** [comment]
Heey, this will be super useful 😩

**Comment by Mazuh** [comment]
just opened a PR about it... I didn't want to open space for multiple eslint choices, I just automated (if user desires it) what was already suggested by the readme file, cause I'm not wanting to start any kind of discussion about code style choices to support nor anything like that right now.
