### ISSUE TITLE
Support ESM for exporting server `--options`

### ISSUE THREAD

**Issue by jstayton** [fastify/fastify-cli#411]
It would be great if ESM projects could `export const options` when using the `--options` flag.

Like this:

```js
export default async (fastify, opts) => {
  // ...
}

export const options = {
  maxParamLength: 200,
}
```

For now, this seems to work:

```js
async function server(fastify, opts) {
  // ...
}

server.options = {
  maxParamLength: 200,
}

export default server
```

Not the end of the world, but I did spin my wheels for a bit thinking `export const options` would just work, since ESM is supported otherwise.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by nooreldeensalah** [comment]
I was gonna start working on this issue, but it seems like that this functionality already exists.

I've tested it on the TypeScript template (which uses ESM format), and it seems to be working.

And if someone wants to double-check the functionality, adding a `console.log(file.options)` after `line 85` in `start.js` should return the exported options object.
https://github.com/fastify/fastify-cli/blob/dd476a793a637da367d278a5041395ef1b909949/start.js#L84-L88

**Comment by nooreldeensalah** [comment]
@jstayton So I've initially tested this behavior on TypeScript, and it worked, this was the reason I've commented.

But indeed, testing it on JavaScript, it doesn't work.

I think it works on TypeScript because it eventually gets compiled to `commonjs` (Attempting to check the script type when using TypeScript in `util.js`  at `line 69` returns `commonjs`). Which is not the case when using ESM in JavaScript (it returns `module`).

So, the reason this doesn't work on `ESM`, is because the function used to load the file (`line 85` in `start.js`) loads only the `default` export.

https://github.com/fastify/fastify-cli/blob/dd476a793a637da367d278a5041395ef1b909949/util.js#L72-L74

@mcollina Please re-open this issue
