### ISSUE TITLE
How to deploy on the production environment

### ISSUE THREAD

**Issue by paulZzhang** [fastify/fastify-cli#68]
How to deploy on the production environment

**Comment by mcollina** [comment]
This is a very long topic. It deploys like any other node application. I would recommend using Docker.

We are currently not generating a dockerfile, but it might make sense to do this.

**Comment by paulZzhang** [comment]
Please add a document how to deploy, Thanks.

**Comment by siddiquiehtesham** [comment]
Is there an example to deploy the microservices in the services directory independently with any lambda functions ?
What platform must be ideal for it or of it is any platform how do we do that because we use some plugins from the plugins directory. So it seems a bit difficult to think about deploying it.
